/*
 * This file was generated by the Gradle 'init' task.
 */
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    //    id("org.springframework.boot") version "2.2.4.RELEASE"
//    id("io.spring.dependency-management") version "1.0.9.RELEASE"
    kotlin("jvm") version "1.3.61"
    kotlin("plugin.spring") version "1.3.61"
    kotlin("plugin.serialization") version "1.3.61"
    application
}

repositories {
    mavenCentral()

}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.springframework.boot:spring-boot-starter:2.2.0.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-web:2.2.0.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-data-mongodb:2.2.0.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-security:2.2.0.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-aop:2.2.0.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-mail:2.2.0.RELEASE")
    implementation("org.springframework.data:spring-data-jpa:2.2.0.RELEASE")
    implementation("org.passay:passay:1.6.0")
    implementation("javax.xml.bind:jaxb-api:2.3.0")
    implementation("io.springfox:springfox-swagger-ui:2.9.2")
    implementation("io.springfox:springfox-swagger2:2.9.2")
    implementation("io.jsonwebtoken:jjwt:0.7.0")
    implementation("org.springframework.boot:spring-boot-configuration-processor:2.2.0.RELEASE")
    implementation("org.apache.commons:commons-collections4:4.1")
    implementation("org.apache.commons:commons-lang3:3.5")
    implementation("com.google.guava:guava:21.0")
    implementation("com.sun.xml.bind:jaxb-core:2.3.0")
    implementation("com.sun.xml.bind:jaxb-impl:2.3.0")
    implementation("org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.2.0.RELEASE")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.61")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.3.61")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.14.0")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.3.61")
    implementation("org.jetbrains.kotlin:kotlin-maven-serialization:1.3.61")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.2.0.RELEASE")
    testImplementation("org.hamcrest:hamcrest-library:2.1")
    testImplementation("junit:junit:4.12")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.3.61")
}

group = "ru.kemsu.openenv"
version = "0.0.1-SNAPSHOT"
description = "OpenenvBackend"

java.sourceCompatibility = JavaVersion.VERSION_1_8

application {
//    mainClassName = "ru.kemsu.openenv.Application"
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "1.8"
    }
}